<a href="https://colab.research.google.com/github/iamvenkateshreddy/Hello_World/blob/master/colab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%tensorflow_version 2.x

In [0]:
import tensorflow as tf


In [0]:
a = tf.constant(2)
b = tf.Variable(3)

In [0]:
b = tf.Variable(3)

In [20]:
c= a*b
c

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [21]:
b = b*b
b

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [0]:
#b.assign(5)

In [0]:
#b.assign_sub(-10)

In [0]:
#b.assign_add(-25)

In [0]:
#b.assign(20)

In [0]:
#b*b

In [27]:
a.numpy()

2

In [28]:
b.numpy()

9

In [29]:
b**b

<tf.Tensor: shape=(), dtype=int32, numpy=387420489>

In [0]:
a = tf.constant([1,2,3,4,5,6],dtype='float32',shape=(2,3))

In [31]:
a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [0]:
b  = tf.constant([6,5,4,3,2,1],dtype='float32',shape=(2,3))

In [33]:
a@b

InvalidArgumentError: ignored

In [0]:
tf.matmul(a,b)

In [0]:
b.numpy().T

In [0]:
b

In [0]:
a@b.numpy().T

In [0]:
a@tf.linalg.matrix_transpose(b)

In [0]:
b

In [0]:
tf.matmul(a,b,transpose_b=True)

In [0]:
b

In [0]:
def f(x):
  return x**2+2*x + tf.math.cos(x)

In [0]:
f(2.0)

In [0]:
x = tf.Variable(1,dtype='float32')

with tf.GradientTape() as g:
  y=f(x)

In [0]:
a = g.gradient(y,x)

In [0]:
print(a)

In [0]:
x=tf.Variable(0,dtype='float32')
x_vals = []
fx_vals = []
df_dx = []
for i in range(100):
  with tf.GradientTape() as g:
    y = f(x)
  x.assign_add(0.5)
  x_vals.append(x.numpy())
  fx_vals.append(f(x).numpy())
  df_dx.append(g.gradient(y,x))
  

In [0]:
import seaborn as sns
%matplotlib inline

In [0]:
import pandas as pd

In [0]:
data = pd.DataFrame({'x_vals':x_vals,'fx_vals':fx_vals,'df_dx':df_dx})

In [0]:
data.head()

In [0]:
sns.scatterplot(data['x_vals'],data['fx_vals'])

In [0]:
sns.scatterplot(data['x_vals'],data['df_dx'])

In [0]:
import numpy as np
import pandas as pd


In [0]:
x1 = np.random.randint(1,30,10)
x2 = np.random.randint(1,30,10)
x = pd.DataFrame({'x1':x1,'x2':x2})

In [36]:
x1,x2,x

(array([ 9, 17, 12, 10, 12, 11, 15, 25, 22, 16]),
 array([ 5, 13,  1, 25, 11, 11, 20, 24, 23,  8]),
    x1  x2
 0   9   5
 1  17  13
 2  12   1
 3  10  25
 4  12  11
 5  11  11
 6  15  20
 7  25  24
 8  22  23
 9  16   8)

In [0]:
y = 4+2*x1+3*x2+3*np.random.random(10)

In [0]:
y

In [38]:
x.shape

(10, 2)

In [0]:
class pred:

  def __init__(self):
    self.w1 = tf.Variable(0.0)
    self.w2 = tf.Variable(0.0)
    self.b  = tf.Variable(0.0)
  
  def __call__(self,x):
    result = self.w1*x.iloc[:,0]+ self.w2*x.iloc[:,1]+self.b
    return  result 

In [0]:
model=pred()

In [41]:
model(x).numpy()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [0]:
def loss(predicted_y,target_y):
  return tf.reduce_mean(tf.squre(predicted_y - target_y))


In [0]:
def train(model,inputs,outputs,learning_rate):
  with tf.GradientTape as g:
    current_loss = loss(model(inputs),outputs)
  dw1,dw2,db = g.gradient(current_loss,[model.w1,model.w2,model.b])
  modle.w1.assign_sub(learning_rate*dw1)
  modle.w2.assign_sub(learning_rate*dw2)
  model.b.assign_sub(learning_rate * db*20)

In [0]:
model = pred()

# Collect the history of W-values and b-values to plot later
w1s,w2s, bs = [], [],[]

epochs = range(50)
for epoch in epochs:
    
    w1s.append(model.w1.numpy())
    w2s.append(model.w2.numpy())
    bs.append(model.b.numpy())
    
    rand_ind=np.random.choice(range(x.shape[0]),100)
    outputs=y[rand_ind]
    inputs=x.iloc[rand_ind,:]
    
    current_loss = loss(model(inputs), outputs)

    train(model, inputs, outputs, learning_rate=0.0001)
    print('Epoch %2d: W1=%1.2f W2=%1.2f b=%1.2f, loss=%2.5f' %
        (epoch, w1s[-1],w2s[-1], bs[-1], current_loss))
    